services:
  frontend:
    build: ./my-app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./flask-backend
    ports:
      - "5000:5000"
    volumes:
      - ./flask-backend:/app
      - ./flask-backend/instance:/app/instance
